Repository yiisoft/yii2-authclient, pull requests merged in 2019-11, with the labels that each got.

#285 Replace JOSE library by JWT Framework
  CHANGELOG.md
  composer.json
  docs/guide-ja/open-id-connect.md
  docs/guide/open-id-connect.md
  src/OpenIdConnect.php
Labels: type:enhancement

#287 Fix missing information in documentation
  composer.json
  docs/guide-ja/open-id-connect.md
  docs/guide/open-id-connect.md
  src/OpenIdConnect.php
Labels: type:docs

#286 Add aleternative statestorage in cache
  CHANGELOG.md
  src/CacheStateStorage.php
Labels: type:enhancement

#288 Default request option for turning off SSL peer verification was removed
  CHANGELOG.md
  UPGRADE.md
  src/BaseClient.php
Labels: severity:security
